import { defineConfig } from 'vitest/config'
import path from 'path'

export default defineConfig({
  test: {
    environment: 'jsdom',
    setupFiles: ['./src/test-setup.ts'],
    // Reset mock state (calls + implementations) before each test so feature
    // tests stay isolated; each test re-declares the responses it needs.
    mockReset: true,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html'],
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        'src/**/*.test.{ts,tsx}',
        'src/test/**',
        'src/lib/__mocks__/**',
        'src/test-setup.ts',
        'src/routeTree.gen.ts', // generated by TanStack Router
        'src/main.tsx', // app entry
        'src/components/ui/**', // vendored shadcn primitives
      ],
    },
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
})
